name: 💍 Tester runner

on:
  workflow_dispatch:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      UI__APP_URL: https://staging.fleeksandbox.xyz
      SDK__GRAPHQL_API_URL: https://graphql.service.staging.fleeksandbox.xyz/graphql
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup .npmrc file to publish to npm
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install
        run: pnpm i
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        
      - name: Build CLI
        run: pnpm build

      - name: Run tests
        run: |
          pnpm test
